[theme]
base = "light"
primaryColor = "#EA7A2F"
backgroundColor = "#EEF2F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172236"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
